music_directory "~/Music"
playlist_directory "~/.mpd/playlists"
db_file "~/.mpd/database"
log_file "~/.mpd/log"
pid_file "~/.mpd/pid"

replaygain "auto"
replaygain_preamp "-10"

audio_output {
    type "osx"
    name "CoreAudio"
    mixer_type "software"
}
